version: "3.8"

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    restart: always
    stdin_open: true
    tty: true
    environment:
      - TZ="Asia/Shanghai"
      # - TRANSMISSION_WEB_HOME=/combustion-release/
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      # - TRANSMISSION_WEB_HOME=/kettu/
      - USER=ryu
      - PASS=19891023
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/md0/transmission/config:/config:rw
      - /mnt/md0/transmission/downloads:/downloads:rw
      - /mnt/md0/transmission/watch:/watch:rw
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    logging:
      driver: "json-file"
      options:
        max-size: "1m"